### PR TITLE
New timeseries node + fixes&updates

### PR DESCRIPTION
**Pull request by cristian-t**
Added the simple timeseries query node.
Added a configurable ID to the aggregate timeseries in node.
Added missing dependency "request" to package.json

### CODE REVIEW

**Comment by kennethmyers** [comment]
First, sorry for the delay in reviewing this pull request. I try to complete them within 24 hours (or sooner) when possible.

Good job limiting each commit to a single "idea". That makes it much easier to review.

Changes I would like to see:

1. On 9e05fb4 make sure this information is also added to the README.
The info panel is meant to be a subset of the README and any changes to the info panel should typically be reflected in the README (and vice versa). 
2. Modify the "Name of Unique Key Field in Incoming JSON" section of the README/Info tab to specify that this field will be providing the column name if the "ID" field is used. Consider changing the name of that field as well to better describe its new role.
3. cce5489 Add documentation in the "Info" tab describing the purpose of the node and how to use. Following the format and style I used for my nodes. Put this info in the README as well and add some content to the README explaining the reasoning behind having the two nodes and when to use which one.

I still need to run some more tests on these and dive into the code further so expect more comments. In the meantime you can add some more commits addressing the above items.

Overall things look good! Nice work!

**Comment by kennethmyers-ibm** [comment]
First, sorry for the delay in reviewing this pull request. I try to complete them within 24 hours (or sooner) when possible.

Good job limiting each commit to a single "idea". That makes it much easier to review.

Changes I would like to see:
1. On 9e05fb4 make sure this information is also added to the README.
   The info panel is meant to be a subset of the README and any changes to the info panel should typically be reflected in the README (and vice versa). 
2. Modify the "Name of Unique Key Field in Incoming JSON" section of the README/Info tab to specify that this field will be providing the column name if the "ID" field is used. Consider changing the name of that field as well to better describe its new role.
3. cce5489 Add documentation in the "Info" tab describing the purpose of the node and how to use. Following the format and style I used for my nodes. Put this info in the README as well and add some content to the README explaining the reasoning behind having the two nodes and when to use which one.

I still need to run some more tests on these and dive into the code further so expect more comments. In the meantime you can add some more commits addressing the above items.

Overall things look good! Nice work!

**Comment by cristian-t** [comment]
Alright, next batch of commits is ready. I've documented everything. I've also renamed the field "Name of Unique Key Field in Incoming JSON" to "Unique Column" and changed documentation accordingly.
Finally, I fixed my node's code to maintain consistency. Before the fix, the code was written so that the end timestamp was before the start timestamp (don't ask why, it's a lengthy explanation).

**Comment by kennethmyers-ibm** [comment]
A few more things:
-Brief test plan that I can follow
-Make sure field names are consistent between my the original nodes and the new "simple node"

**Comment by kennethmyers-ibm** [comment]
Great job! I will accept the pull request.

**Pull request merged**
